### ISSUE TITLE
The related model 'App\Models\...' must either extend 'Awobaz\Compoships\Database\Eloquent\Model' or use the 'Awobaz\Compoships\Compoships' trait

### ISSUE THREAD

**Issue by s1lviu** [topclaudy/compoships#62]
On Laravel 5.8 
![image](https://user-images.githubusercontent.com/9863576/64912014-bd407c00-d731-11e9-9245-f19749c71c08.png)

My model looks like this:

```
<?php

namespace App\Models;

use App\Models\Auth\User;
use Illuminate\Database\Eloquent\Model;

class UserGroups extends Model
{
    use \Awobaz\Compoships\Compoships;

    public function keywords()
    {
        return $this->hasMany(UserGroupKeywords::class, ['user_id', 'fb_group_id'], ['user_id', 'fb_group_id']);
    }
```

**Comment by s1lviu** [comment]
Fixed after added the trait `use \Awobaz\Compoships\Compoships;` in the referred model too.

**Comment by DerkJanSpeelman** [comment]
I'm still getting this error, since I'm extending my Model with a generated BaseModel (that on its turn extends the default Eloquent\Model)...
